"""empty message

Revision ID: cbe84d0168cf
Revises: None
Create Date: 2016-07-28 06:10:41.316971

"""

# revision identifiers, used by Alembic.
revision = 'cbe84d0168cf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entries', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_column('entries', 'author_id')
    ### end Alembic commands ###
